import type { Metadata } from "next";
import "./globals.css";

import { Alexandria } from "next/font/google"
import Navbar from "@/components/Home/Navbar";
import Header from "@/components/Home/Header";
import Footer from "@/components/Home/Footer";

const alexand = Alexandria({
  weight: ['200','300','400','500','600','700','800','900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Mastering Engineering",
  description: "Generated by create next app",
  icons:{
    icon:"/assets/imgs/main-logo.png"
  }
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode}>) {
  return (
    <html lang="en" className={alexand.className}>
      <body className="w-screen min-h-screen font-extralight overflow-x-hidden ">
          <Navbar />
            <main>
              <Header />
              {children}
            </main>
        <Footer />
      </body>
    </html>
  );
}
